### ISSUE TITLE
Docker Image of the project

### ISSUE THREAD

**Issue by altodd** [byalextran/southwest-headers#3]
Hey! I appreciate the work on getting the headers, etc. figured out. I found your project from the python version we were commenting on. I made it all into a [docker image](https://hub.docker.com/r/altodd/southwest-docker) and plan to keep it updated as much as possible. I put the Dockerfile, etc [over on my github](https://github.com/altodd/Southwest-Docker), I'd love to hear your thoughts. In function it works like the docker container they had over on the python version of the project. I haven't gotten to do tons of testing yet, but have a check-in tomorrow and plan to do more testing after travel. Feel free to close this issue, I just opened it to hear what you had to say.

**Comment by QuiGonLeong** [comment]
@altodd - This is great and makes it really to deploy. I've pulled your image to test for an upcoming flight Sunday. Thanks

**Comment by byalextran** [comment]
thanks for doing this! i haven't played around with docker so can't really provide much feedback. 

as an aside, i know there are some things i can do to streamline the installation this project. will work on those changes this upcoming week that could simplify things on the docker end as well.
